base_url = "http://127.0.0.1:8000/"
db_conn_string = "host=localhost port=5432 user=webuser password=shoopihoo9yoosah0Run2queeteufeiJ dbname=sharpircbot"
http_listen = "127.0.0.1:8000"
auth_tokens = [
    'dsEcJWLSHPvG4qN7HGxmz1khpMP6sf1xadLHhlxXgxbAq1L8sY5TDtSWqRpCYrPX',
]

[hours]
morning_start = 5
morning_end = 13
midday_start = 11
midday_end = 20
evening_start = 17
