name: beepee debug build
on: [push]
jobs:
  build-arch-debug:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: check out repository code
        uses: actions/checkout@v2
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install build dependencies
        run: pacman -S --needed --noconfirm cargo python
      - name: check for forgotten templates and static files
        run: python cicd/check_templates_statics.py
      - name: fetch dependencies
        run: sh ./cicd/cargo_fetch.sh
      - name: run debug build
        run: cargo build
      - name: run debug tests
        run: cargo test
      - name: upload debug binary
        uses: actions/upload-artifact@v2
        with:
          name: beepee-debug
          path: target/debug/beepee
